name: Sync Repos

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Git User Info
        run: |
          git config --global user.email "work.adityasodha@gmail.com"
          git config --global user.name "Adityasinh-Sodha"

      - name: Unshallow Clone (if needed)
        run: |
          if [ -f .git/shallow ]; then
            git fetch --unshallow
          else
            echo "Repository is already complete. No need to unshallow."
          fi

      - name: Pull from GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB }}
        run: |
          git remote add gitlab https://Adityasinh-Sodha:$GITLAB_TOKEN@gitlab.com/Adityasinh-Sodha/Encrypted-Messaging-System.git
          git fetch gitlab main
          git rebase gitlab/main || git rebase --skip

      - name: Push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB }}
        run: |
          git push gitlab main
